name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      TF_VAR_rg_name: ${{ secrets.RESOURCE_GROUP }}
      TF_VAR_storage_name: ${{ secrets.STORAGE_ACCOUNT }}
      TF_VAR_container_name: ${{ secrets.CONTAINER }}
      TF_VAR_key_name: ${{ secrets.KEYNAME }}
      TF_VAR_service_principal_name: ${{ secrets.SERVICE_PRINCIPAL }}
      TF_VAR_keyvault_name: ${{ secrets.KEYVAULT }}
      TF_VAR_ssh_public_key: ${{ secrets.PUBLIC_KEY }}
      tf_actions_working_dir: ./terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: terraform apply
        run: terraform apply -auto-approve

      # - name: Destroy Infra
      #   run: terraform destroy -auto-approve
